# Generated by Django 4.2.7 on 2023-11-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['-user'], name='accounts_pr_user_id_a2148d_idx'),
        ),
    ]
